//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22101_vnukova_autorization.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        public long PolzovatelID { get; set; }
        public string Name { get; set; }
        public string Familia { get; set; }
        public string Login { get; set; }
        public Nullable<long> Password { get; set; }
        public Nullable<long> RoleId { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
